// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi7jWHICp9JoqPeqaTY0oFAwreDq5CCZA',
    appId: '1:71902093466:web:68335a008b972ce5dd7f23',
    messagingSenderId: '71902093466',
    projectId: 'rupixa-ai-d2b6e',
    authDomain: 'rupixa-ai-d2b6e.firebaseapp.com',
    storageBucket: 'rupixa-ai-d2b6e.firebasestorage.app',
    measurementId: 'G-ZB6VXXJM6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO5ByQSYhL2OlJWxCF9YsWpXEPKD2Oy08',
    appId: '1:71902093466:android:94a6906750f2b771dd7f23',
    messagingSenderId: '71902093466',
    projectId: 'rupixa-ai-d2b6e',
    storageBucket: 'rupixa-ai-d2b6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQ03BIFqvb72icUJPL290JXY-QnV0WHc',
    appId: '1:71902093466:ios:e6dc8adc83b48b6fdd7f23',
    messagingSenderId: '71902093466',
    projectId: 'rupixa-ai-d2b6e',
    storageBucket: 'rupixa-ai-d2b6e.firebasestorage.app',
    iosBundleId: 'com.example.rupixaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQ03BIFqvb72icUJPL290JXY-QnV0WHc',
    appId: '1:71902093466:ios:e6dc8adc83b48b6fdd7f23',
    messagingSenderId: '71902093466',
    projectId: 'rupixa-ai-d2b6e',
    storageBucket: 'rupixa-ai-d2b6e.firebasestorage.app',
    iosBundleId: 'com.example.rupixaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi7jWHICp9JoqPeqaTY0oFAwreDq5CCZA',
    appId: '1:71902093466:web:ea72b52f27e65d00dd7f23',
    messagingSenderId: '71902093466',
    projectId: 'rupixa-ai-d2b6e',
    authDomain: 'rupixa-ai-d2b6e.firebaseapp.com',
    storageBucket: 'rupixa-ai-d2b6e.firebasestorage.app',
    measurementId: 'G-Q92Q03ZVMR',
  );

}